# Generated by Django 6.0.6 on 2026-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("TEPAT_WAKTU", "Tepat Waktu"),
                    ("TERLAMBAT", "Terlambat"),
                ],
                default="TEPAT_WAKTU",
                max_length=20,
            ),
        ),
    ]
