# Generated by Django 6.0.6 on 2026-06-25 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="jam_masuk",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="tanggal",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
